#!/bin/bash
# Production Deployment Commands
# Copy and run these commands in order
# ============================================================================

echo "🚀 PRODUCTION DEPLOYMENT - Step-by-Step Commands"
echo "============================================================================"

# ============================================================================
# PHASE 1: MERGE CODE TO MAIN
# ============================================================================
echo ""
echo "PHASE 1: Merge code from staging to main"
echo "--------"
echo ""
echo "Option A - Via CLI:"
echo "  1. Create PR:"
echo "     gh pr create --title 'Merge staging: Restore 56 DC teachers'"
echo ""
echo "  2. Get PR number from output, then merge:"
echo "     gh pr merge <PR_NUMBER> --merge"
echo ""
echo "Option B - Via GitHub UI:"
echo "  1. Go to: https://github.com/Orenda-Project/coaching-platform/pulls"
echo "  2. Find your PR and click 'Merge pull request'"
echo "  3. Confirm merge"
echo ""
echo "Verify merge succeeded:"
echo "  git log main -1 --oneline"
echo "  # Should show your merge commit"
echo ""
read -p "Press Enter after merging to main..."

# ============================================================================
# PHASE 2: DEPLOY APP TO PRODUCTION
# ============================================================================
echo ""
echo "PHASE 2: Deploy app to production (Railway)"
echo "--------"
echo ""
echo "Check if auto-deploy is enabled on Railway:"
echo "  1. Go to: https://railway.app"
echo "  2. Select: coaching-platform project"
echo "  3. Select: app service (Node.js)"
echo "  4. Settings → Deployments → Auto Deploy"
echo ""
echo "If auto-deploy is OFF, manually deploy:"
echo "  railway deploy --service app --environment production"
echo ""
echo "Monitor deployment:"
echo "  railway logs --service app --environment production --follow"
echo ""
read -p "Press Enter after app is deployed and live..."

# ============================================================================
# PHASE 3: APPLY MIGRATIONS TO PRODUCTION DATABASE
# ============================================================================
echo ""
echo "PHASE 3: Apply migrations to production database (Supabase)"
echo "--------"
echo ""
echo "Step 3.1 - Link to production Supabase project:"
echo "  supabase link --project-ref agziuwqpkfmxtospfxns"
echo ""
echo "Step 3.2 - Review migrations (DRY RUN - SAFE):"
echo "  supabase db push --dry-run"
echo ""
echo "⚠️  CRITICAL: Verify output shows ONLY these 2 migrations:"
echo "  • 20260515000001_seed_all_56_dc_teachers.sql"
echo "  • 20260515000002_deduplicate_staging_teachers.sql"
echo ""
echo "If other migrations appear, DO NOT PROCEED. Contact team lead."
echo ""
read -p "Press Enter after reviewing and confirming the dry-run..."

echo ""
echo "Step 3.3 - Apply migrations (WILL MODIFY DATABASE):"
echo "  supabase db push --yes"
echo ""
read -p "Press Enter after migrations are applied..."

echo ""
echo "Step 3.4 - Verify data in production:"
echo "  Open: https://app.supabase.com"
echo "  Project: agziuwqpkfmxtospfxns (production)"
echo "  SQL Editor → Run:"
echo ""
echo "    SELECT COUNT(*) as total FROM public.teacher_dc_scores;"
echo "    -- Expected result: 56"
echo ""
echo "    SELECT teacher_name, school_name, region, COUNT(*) as cnt"
echo "    FROM public.teacher_dc_scores"
echo "    GROUP BY teacher_name, school_name, region"
echo "    HAVING COUNT(*) > 1;"
echo "    -- Expected result: 0 rows (no duplicates)"
echo ""
echo "    SELECT DISTINCT region FROM public.teacher_dc_scores ORDER BY region;"
echo "    -- Expected regions: B.K, Nilore, Sihala, Tarnol, Urban-I, Urban-II"
echo ""
read -p "Press Enter after verifying production data..."

# ============================================================================
# PHASE 4: SMOKE TEST PRODUCTION APP
# ============================================================================
echo ""
echo "PHASE 4: Smoke test production app"
echo "--------"
echo ""
echo "Test 1 - Signup:"
echo "  1. Open production URL (check ENVIRONMENT_SUMMARY.md for URL)"
echo "  2. Click 'Sign Up'"
echo "  3. Create test account:"
echo "     Email: test.prod.$(date +%s)@taleemabad.com"
echo "     Password: TestPass123!"
echo "  4. Complete onboarding"
echo "  ✓ Signup succeeds"
echo "  ✓ Onboarding shows modules"
echo ""
read -p "Press Enter after testing signup..."

echo ""
echo "Test 2 - SmartSchedule Dashboard:"
echo "  1. Login to production"
echo "  2. Go to 'SmartSchedule' → 'Neo Dashboard'"
echo "  3. Verify teachers display:"
echo "     ✓ Exactly 56 teachers (no duplicates)"
echo "     ✓ All regions: B.K, Nilore, Sihala, Tarnol, Urban-I, Urban-II"
echo "     ✓ Teachers sorted by DC score"
echo ""
read -p "Press Enter after testing SmartSchedule..."

echo ""
echo "Test 3 - Core Flows:"
echo "  ✓ Baseline assessment completes"
echo "  ✓ Module 1 loads and quiz works"
echo "  ✓ Module unlock logic works"
echo "  ✓ Certificate generates after endline"
echo "  ✓ No 'table not found' errors in browser console"
echo ""
read -p "Press Enter after testing core flows..."

echo ""
echo "Test 4 - Check logs for errors:"
echo "  railway logs --service app --environment production --since 30m | grep -i error"
echo "  # Should return no error lines"
echo ""
read -p "Press Enter after checking logs..."

# ============================================================================
# PHASE 5: FINAL VERIFICATION
# ============================================================================
echo ""
echo "PHASE 5: Final verification"
echo "--------"
echo ""
echo "Step 5.1 - Verify git history:"
echo "  git log main -5 --oneline"
echo "  # Should show your merge commits"
echo ""
echo "Step 5.2 - Document deployment:"
echo "  Save this in deployment log:"
echo "    - Date/Time: $(date)"
echo "    - What: Deployed 56 DC teachers + deduplication"
echo "    - Branch: main"
echo "    - Migrations: 20260515000001, 20260515000002"
echo "    - Status: ✅ Complete"
echo ""
read -p "Press Enter after final verification..."

# ============================================================================
# SUCCESS
# ============================================================================
echo ""
echo "✅ DEPLOYMENT COMPLETE!"
echo "============================================================================"
echo ""
echo "Summary:"
echo "  ✅ Code merged to main"
echo "  ✅ App deployed to production"
echo "  ✅ Migrations applied to production DB"
echo "  ✅ All 56 teachers in production (no duplicates)"
echo "  ✅ SmartSchedule NEO functional"
echo "  ✅ All smoke tests passed"
echo ""
echo "What's next:"
echo "  1. Monitor production logs for next 24 hours"
echo "  2. Gather user feedback"
echo "  3. Create post-deployment report"
echo ""

