/* eslint-disable react-hooks/exhaustive-deps */
import { useState, useEffect } from 'react';
import { patchObservation } from '@/data/observations';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { toast } from 'sonner';
import type { CotObservation } from '@/types/observation';
import { Save, Eye, MessageSquare, Cpu } from 'lucide-react';

interface Props {
  observation: CotObservation;
  onSaved: (updated: CotObservation) => void;
}

export function DebriefForm({ observation, onSaved }: Props) {
  const [hotsNotes, setHotsNotes] = useState(observation.hots_notes || '');
  const [notes, setNotes] = useState(observation.notes_for_teacher || '');
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    setHotsNotes(observation.hots_notes || '');
    setNotes(observation.notes_for_teacher || '');
  }, [observation.id]);

  const handleSave = async () => {
    setSaving(true);
    try {
      const updated = await patchObservation(observation.id, {
        hots_notes: hotsNotes.trim() || null,
        notes_for_teacher: notes.trim() || null,
      });

      toast.success('Debrief notes saved!');
      onSaved(updated);
    } catch {
      toast.error('Failed to save notes');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="space-y-5">
      {/* Observation Notes */}
      <div className="space-y-2">
        <Label htmlFor="hots-notes" className="flex items-center gap-2 text-sm flex-wrap">
          <Eye className="w-4 h-4 text-blue-500" />
          Observation Notes
          <span className="text-xs text-muted-foreground font-normal">
            (what you observed during the lesson)
          </span>
          {observation.dc_status === 'completed' && observation.hots_notes && (
            <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded bg-blue-50 border border-blue-200 text-xs text-blue-600 font-normal">
              <Cpu className="w-3 h-3" /> Generated by DC
            </span>
          )}
        </Label>
        <Textarea
          id="hots-notes"
          placeholder="Describe key moments, patterns and behaviors you observed during the lesson..."
          value={hotsNotes}
          onChange={e => setHotsNotes(e.target.value)}
          rows={4}
          className="resize-none"
        />
        <p className="text-xs text-muted-foreground text-right">{hotsNotes.length} characters</p>
      </div>

      {/* Feedback for Teacher */}
      <div className="space-y-2">
        <Label htmlFor="debrief-notes" className="flex items-center gap-2 text-sm">
          <MessageSquare className="w-4 h-4 text-green-500" />
          Feedback for Teacher
          <span className="text-xs text-muted-foreground font-normal">
            (what you shared in the debrief)
          </span>
        </Label>
        <Textarea
          id="debrief-notes"
          placeholder="Write the feedback and action points you discussed with the teacher during the debrief session..."
          value={notes}
          onChange={e => setNotes(e.target.value)}
          rows={5}
          className="resize-none"
        />
        <p className="text-xs text-muted-foreground text-right">{notes.length} characters</p>
      </div>

      {/* Tips */}
      <div className="bg-muted/40 rounded-lg p-3">
        <p className="text-xs font-medium text-foreground mb-1.5">Debrief Tips</p>
        <ul className="text-xs text-muted-foreground space-y-1 list-disc list-inside">
          <li>Start with what the teacher did well</li>
          <li>Be specific — reference moments from the lesson</li>
          <li>Focus on 1–2 key areas for improvement</li>
          <li>Agree on concrete next steps together</li>
        </ul>
      </div>

      <Button onClick={handleSave} disabled={saving} className="w-full">
        <Save className="w-4 h-4 mr-2" />
        {saving ? 'Saving...' : 'Save Debrief Notes'}
      </Button>
    </div>
  );
}
